<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contracts\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Config\buffs.json" />
    <EmbeddedResource Include="Config\skills.json" />
    <EmbeddedResource Include="Config\monsterskills.json" />
    <EmbeddedResource Include="Config\items.json" />
    <EmbeddedResource Include="Config\consumableShop.json" />
    <EmbeddedResource Include="Config\systemShop.json" />
    <EmbeddedResource Include="Config\userConfig.json" />
  </ItemGroup>

</Project>