// <auto-generated />
using System;
using BlazorIdle.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorIdle.Server.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251125065006_UpdateDefaultMaxCharacterSlots")]
    partial class UpdateDefaultMaxCharacterSlots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BlazorIdle.Shared.Models.CharacterData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AccountFlags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "accountFlags");

                    b.Property<string>("ActiveCombatProfessionId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("warrior")
                        .HasAnnotation("Relational:JsonPropertyName", "activeCombatProfessionId");

                    b.Property<double>("AttackRateAPS")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "attackRateAPS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<double>("CritChancePercent")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "critChancePercent");

                    b.Property<double>("CritMultiplier")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "critMultiplier");

                    b.Property<int>("DamagePerAttack")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "damagePerAttack");

                    b.Property<string>("EquippedSkillsByProfession")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "equippedSkillsByProfession");

                    b.Property<string>("FixedSkillsByProfession")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "fixedSkillsByProfession");

                    b.Property<double>("HastePercent")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "hastePercent");

                    b.Property<string>("LearnedSkills")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "learnedSkills");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "maxHp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("ProfessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "professionId");

                    b.Property<string>("Professions")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "professions");

                    b.Property<string>("PurchaseState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "purchaseState");

                    b.Property<double>("ReviveSec")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "reviveSec");

                    b.Property<int>("SpecialDamage")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "specialDamage");

                    b.Property<double>("SpecialIntervalSec")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "specialIntervalSec");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.Property<double>("VariancePct")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "variancePct");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("BlazorIdle.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountPurchaseState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCharacterSlots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsedCharacterSlots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorIdle.Shared.Models.CharacterData", b =>
                {
                    b.OwnsOne("BlazorIdle.Shared.Models.Inventory", "Inventory", b1 =>
                        {
                            b1.Property<string>("CharacterDataId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CharacterId")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "characterId");

                            b1.Property<string>("Id")
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "id");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "lastUpdated");

                            b1.HasKey("CharacterDataId");

                            b1.ToTable("Characters");

                            b1
                                .ToJson("Inventory")
                                .HasAnnotation("Relational:JsonPropertyName", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("CharacterDataId");

                            b1.OwnsMany("BlazorIdle.Shared.Models.ItemInstance", "Items", b2 =>
                                {
                                    b2.Property<string>("InventoryCharacterDataId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<DateTime>("AcquiredAt")
                                        .HasColumnType("TEXT")
                                        .HasAnnotation("Relational:JsonPropertyName", "acquiredAt");

                                    b2.Property<string>("ItemId")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasAnnotation("Relational:JsonPropertyName", "itemId");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("INTEGER")
                                        .HasAnnotation("Relational:JsonPropertyName", "quantity");

                                    b2.HasKey("InventoryCharacterDataId", "__synthesizedOrdinal");

                                    b2.ToTable("Characters");

                                    b2.HasAnnotation("Relational:JsonPropertyName", "items");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryCharacterDataId");
                                });

                            b1.Navigation("Items");
                        });

                    b.Navigation("Inventory")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
